# Generated by Django 5.2.8 on 2025-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('guest_count', models.IntegerField()),
                ('reservation_date', models.DateTimeField(auto_now=True)),
                ('commants', models.CharField(max_length=200)),
            ],
        ),
    ]
