# Generated by Django 5.2.8 on 2025-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
