# Generated by Django 6.0.1 on 2026-01-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_payment'),
    ]

    operations = [

        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Unpaid Bill'), (1, 'Bill Paid ')], default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
    ]
