# Generated by Django 6.0.1 on 2026-01-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_commants_reservation_comments_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
