# Generated by Django 6.0.1 on 2026-01-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_commants_reservation_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='commants',
            new_name='comments',
        ),
    ]
